### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by compilekaiten** [zynth17/vitailse#69]
Used Vitailse as a template.
Cloned to my computer.
Ran `pnpm i` with no problems.
Ran `pnpm dev` with no problems.

Running `pnpm build` fails everytime with the following issue:
```
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
C:\Users\Fortress\Desktop\vitalise\node_modules\.pnpm\vue-router@4.1.2_vue@3.2.37\node_modules\vue-router\dist\vue-router.prod.cjs:430
    const { history, location } = window;
                                  ^

ReferenceError: window is not defined
    at useHistoryStateNavigation (C:\Users\Fortress\Desktop\vitalise\node_modules\.pnpm\vue-router@4.1.2_vue@3.2.37\node_modules\vue-router\dist\vue-router.prod.cjs:430:35)
    at Object.createWebHistory (C:\Users\Fortress\Desktop\vitalise\node_modules\.pnpm\vue-router@4.1.2_vue@3.2.37\node_modules\vue-router\dist\vue-router.prod.cjs:517:31)
    at Module.<anonymous> (C:\Users\Fortress\Desktop\vitalise\.vite-ssg-temp\main.cjs:2914:22)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at build (file:///C:/Users/Fortress/Desktop/vitalise/node_modules/.pnpm/vite-ssg@0.20.2_zodgg63wx4ia7g264h7fi3aaae/node_modules/vite-ssg/dist/chunks/build.mjs:171:115)

Node.js v18.4.0
 ELIFECYCLE  Command failed with exit code 1.
```

Tried to install `workbox-window` but that doesn't help, and just gives me this warning: 
```
 WARN  Issues with peer dependencies found
.
└─┬ vite-plugin-vue-layouts
  └── ✕ unmet peer vite@^2.5.0: found 3.0.0
  ```

**Comment by zynth17** [comment]
does installing workbox-window make the build works? if yes then you can supress the pnpm warning `strict-peer-dependencies` on `.npmrc`
currently i still have no time to fixed this issue. pr are welcome.

**Comment by compilekaiten** [comment]
Installing `workbox-window` does NOT fix the build.

I am too smooth brain to fix this myself. Hopefully someone else can PR. Thanks

**Comment by zynth17** [comment]
@compilekaiten have you found a way to fix?

**Comment by compilekaiten** [comment]
> @compilekaiten have you found a way to fix?

Negative. I'm too stupid to fix it myself.

**Comment by mfazail** [comment]
In vite.config.ts file 

```js
ssgOptions: {
		script: 'async',
		formatting: 'minify',
		format: 'cjs',
		mock: true, // add this
	},
```
