### ISSUE TITLE
Fresh repo clone and build fails

### ISSUE THREAD

**Issue by veritymedia** [zynth17/vitailse#81]
I was getting vite-ssg build errors on my project, decided to check on a clean install. Repo without any modifications fails vite-ssg build.

` Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
C:\Code\TEST_REPOS\vitailse-test\node_modules\.pnpm\vue-router@4.1.2_vue@3.2.37\node_modules\vue-router\dist\vue-router.prod.cjs:430
    const { history, location } = window;
                                  ^

ReferenceError: window is not defined
    at useHistoryStateNavigation (C:\Code\TEST_REPOS\vitailse-test\node_modules\.pnpm\vue-router@4.1.2_vue@3.2.37\node_modules\vue-router\dist\vue-router.prod.cjs:430:35)
    at Object.createWebHistory (C:\Code\TEST_REPOS\vitailse-test\node_modules\.pnpm\vue-router@4.1.2_vue@3.2.37\node_modules\vue-router\dist\vue-router.prod.cjs:517:31)
    at Module.<anonymous> (C:\Code\TEST_REPOS\vitailse-test\.vite-ssg-temp\main.cjs:2914:22)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at build (file:///C:/Code/TEST_REPOS/vitailse-test/node_modules/.pnpm/vite-ssg@0.20.2_zodgg63wx4ia7g264h7fi3aaae/node_modules/vite-ssg/dist/chunks/build.mjs:171:115)
 ELIFECYCLE  Command failed with exit code 1.`

**Comment by veritymedia** [comment]
Fix:

/modules/router.ts

```
+ const isClient = process.env.SSR ? false : true
```
```
- history: createWebHistory()
+ history: isClient ? createMemoryHistory() : createWebHistory()
```

createMemoryHistory imported from "@vue-router"

**Comment by mfazail** [comment]
In vite.config.ts add following line

```js
ssgOptions: {
                ...
		mock: true, // add this
	},
```

**Comment by zynth17** [comment]
done on the latest update
